### ISSUE TITLE
Changing style of radio buttons

### ISSUE THREAD

**Issue by youssefMagdy29** [Youssef-Emad/sQuiz#12]

**Comment by youssefMagdy29** [comment]
@HaithamKhedr @heshaam-abubakr

![screenshot from 2015-02-03 20 23 41](https://cloud.githubusercontent.com/assets/9354305/6026395/2c627982-abe3-11e4-8ef2-231a6b8c4db3.png)

**Comment by heshaam-abubakr** [comment]
joe hwa kda el default 3l student wala eh?

**Comment by youssefMagdy29** [comment]
لأ ده انا بس عشان اوضح شكله عامل ازاي لما يكون checked
